import java.io.File;
import java.util.Properties;    
import javax.mail.*;    
import javax.mail.internet.*;    
import javax.mail.PasswordAuthentication;
import javax.swing.JFileChooser;
import javax.activation.FileDataSource;
import javax.activation.DataHandler;
import javax.mail.Authenticator;

 


/**
 *
 * @author TheSuMiT.
 */
public class AirMail extends javax.swing.JFrame {

    /**
     * Creates new form AirMail
     */
    public AirMail() {
        initComponents();
    
    
    }


//decarations for travelling of data from one method to another.
  FileDataSource source = null;
    String file_path =  null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ping_mail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        to_id = new javax.swing.JTextField();
        from_id = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        heart = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        get_passcode = new javax.swing.JPasswordField();
        attach_file = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Karumbi", 1, 48)); // NOI18N
        jLabel1.setText("Air-Mail");

        ping_mail.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        ping_mail.setText("Let-Fly !");
        ping_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ping_mailActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 57, 65));
        jLabel2.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 19, 11));
        jLabel2.setText("From :");

        jLabel3.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 16, 1));
        jLabel3.setText("To :");

        jLabel4.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 31, 11));
        jLabel4.setText("Sub  :");

        jLabel5.setText("(2.0v)");

        jLabel6.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(12, 12, 1));
        jLabel6.setText("Heart :");

        to_id.setToolTipText("Enter Gmail  Id ");

        from_id.setToolTipText("Enter Gmail Id");

        sub.setToolTipText("Subject of Mail !");

        heart.setColumns(20);
        heart.setRows(5);
        heart.setToolTipText("Enter Main Content  of the Mail !");
        jScrollPane1.setViewportView(heart);

        jLabel7.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Passcode :");

        get_passcode.setToolTipText("Passcode  Please !");
        get_passcode.setEchoChar('#');

        attach_file.setText("Attach File");
        attach_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_fileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(get_passcode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(to_id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(from_id)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(attach_file, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ping_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(from_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_passcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attach_file))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ping_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


 //---------------------------------------------------------------------------------------------------------------
    	public  void attach_fileActionPerformed(java.awt.event.ActionEvent evt) 

{//GEN-FIRST:event_attach_fileActionPerformed
        
     try{ 
          
       
        
        
        JFileChooser fileChooser = new JFileChooser();
    

    	fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    	int result = fileChooser.showOpenDialog(this);
    


        System.out.println("Selected file: " + result );											
    																				
    
  
        


        File selectedFile = fileChooser.getSelectedFile();
        file_path = selectedFile.getAbsolutePath();
        System.out.println("Selected file: " + file_path );							//Displaying selected file path in CMD	
    
        
        
        attach_file.setText("1 File Attach !");
   
      
  
                                                                                                   
	    FileDataSource source = new FileDataSource(file_path);  

       }   
        
       catch (Exception e) {e.printStackTrace();}  

 }																									//attach_file method   [END]

 //-----------------------------------------------------------------------------------------------------------------



    public void ping_mailActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_ping_mailActionPerformed
        
         
        
 		String sender_id , receiver_id , subject, content  ="";

        sender_id =  from_id.getText();
        receiver_id=to_id.getText();
        subject= sub.getText();
  		 content= heart.getText();

        
        
          final  char getpass[] = get_passcode.getPassword();								//fetching  passcode from textfield
          
          final  String  passcode = String.valueOf(getpass);
        
                                                                           
 
		    Authenticator auth = new Authenticator() {										//Checking Credentials
            	
                // override the getPasswordAuthentication method
                protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(sender_id,passcode);
                }
        };





        																				 //   Mail Hosting Provided by     [Gmail] 	

          Properties props = new Properties();    										//Setting Properties of for Sending Mail  
              props.put("mail.smtp.host", "smtp.gmail.com");    
              props.put("mail.smtp.socketFactory.port", "465");    
              props.put("mail.smtp.socketFactory.class",    
                        "javax.net.ssl.SSLSocketFactory");    
              props.put("mail.smtp.auth", "true");    
              props.put("mail.smtp.port", "465");  

        Session session = Session.getDefaultInstance(props, auth);





   
   try {    
 

               MimeMessage message = new MimeMessage(session);    
 

		       message.addRecipient(Message.RecipientType.TO,new InternetAddress(receiver_id));   
	      

       	       message.setSubject(subject);																	//Setting 	[Subject of Mail]			    
               
               
            


			MimeBodyPart messageBodyPart1 = new MimeBodyPart();  
    		messageBodyPart1.setText(content);																//Setting    [Body Part] 

    
    	  MimeBodyPart bodypart2 = new MimeBodyPart();  	
	
		    bodypart2.setDataHandler(new DataHandler(source));  
			bodypart2.attachFile(file_path);   															// Attaching  [file]				



	     
	        Multipart   multipart = new MimeMultipart();  
	    	multipart.addBodyPart(messageBodyPart1);  
	    	multipart.addBodyPart(bodypart2);  






               message.setContent(multipart);  																//Setting Entire Mail Content

               Transport.send(message);    																	//	[Sending Mail]
               System.out.println("\n Message sent successfully : ");
               
		   
		

		        sub.setText("");											//Clearing Entered Data of fields :  Sub,Heart,Recipients_id  &  Attached File 
		        heart.setText("");
		        to_id.setText("");
		        attach_file.setText("Attach File !");
        
             
  
	
} 

	catch (Exception e) {throw new RuntimeException(e);}

         
         
        
    }																			//Ping_Mail Method END								
 //----------------------------------------------------------------------------------------------------------------------


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                new AirMail().setVisible(true);
            }
        });
    
    
  
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach_file;
    private javax.swing.JTextField from_id;
    private javax.swing.JPasswordField get_passcode;
    private javax.swing.JTextArea heart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ping_mail;
    private javax.swing.JTextField sub;
    private javax.swing.JTextField to_id;
    // End of variables declaration//GEN-END:variables
}
